# Generated by Django 5.0b1 on 2023-11-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classviewshome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Фамилия')),
                ('image_profile1', models.ImageField(upload_to='image', verbose_name='Фото профиля')),
                ('your_country', models.CharField(blank=True, max_length=250, null=True, verbose_name='Страна')),
                ('your_city', models.CharField(blank=True, max_length=250, null=True, verbose_name='Город')),
            ],
        ),
    ]
