# Generated by Django 5.0b1 on 2023-11-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classviewshome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_profile',
            field=models.ImageField(upload_to='image/', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image_profile1',
            field=models.ImageField(upload_to='image/', verbose_name='Фото профиля'),
        ),
    ]
