# Generated by Django 5.0b1 on 2023-10-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classviewshome', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='article',
        ),
        migrations.AddField(
            model_name='book',
            name='article',
            field=models.ManyToManyField(to='classviewshome.article', verbose_name='Статьи'),
        ),
    ]
